server:
  port: 8094

spring:
  application:
    name: CodeByZ
  datasource:
    url: jdbc:postgresql://localhost:5432/codebyzplatform
    username: postgres
    password: 122333
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        jdbc:
          time_zone: UTC

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  access-token-minutes: 60
  refresh-token-days: 30

oauth:
  frontend-base-url: http://localhost:3000

sendgrid:
  enabled: true
  api-key: ${SEND_GRID}
  from-email: codebyzplatform@gmail.com
  from-name: CodeByZ

storage:
  base-url: ${BACKEND:https://codebyz.online}
  uploads-dir: files
#  uploads-dir-config: files
  public-base-url: ${BACKEND:https://codebyz.online}/files
  profile:
    base:
      url: files/profile

verification:
  sign-up-code-minutes: 10
  sign-in-code-minutes: 10

admin:
  seed:
    enabled: true
    email: ziyatovzafar98@gmail.com
    username: admin
    full-name: CodeByZ Admin
    password: Zafar123$

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs
